stages:
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

test:
  stage: test
  image: python:$VERSION
  script:
    - echo "Testing on Python $VERSION"
    - python --version
    - curl -sSL https://install.python-poetry.org | python -
    - export PATH="/root/.local/bin:$PATH"
    - poetry update
    - poetry build
    - poetry install -v
    - poetry run invoke test
  only:
    - master
  parallel:
    matrix:
      - VERSION: ['3.10', '3.11', '3.12']

deploy_to_pypi:
  stage: deploy
  image: $ARCH/python:$VERSION
  script:
    - echo "Building for Python $VERSION on $ARCH"
    - curl -sSL https://install.python-poetry.org | python -
    - export PATH="/root/.local/bin:$PATH"
    - poetry update
    - poetry build
    - poetry config pypi-token.pypi $PYPI_API_TOKEN
    - poetry publish --skip-existing
  only:
    - master
  parallel:
    matrix:
      - ARCH: amd64
        VERSION: ['3.9', '3.10', '3.11', '3.12']
      - ARCH: i386
        VERSION: ['3.9', '3.10', '3.11', '3.12']
      - ARCH: arm32v7
        VERSION: ['3.9', '3.10', '3.11', '3.12']
      - ARCH: arm64v8
        VERSION: ['3.9', '3.10', '3.11', '3.12']
